### ISSUE TITLE
Vendor blobs

### ISSUE THREAD

**Issue by RaymondSchnyder** [frantisheq/local_manifests#1]
Hey!

I saw you  are using a private repo for your vendor blobs, would you share them with me?
I want to compile my own pie rom with your device tree, but im not able to as i lack some blobs which are also not in the themuppets repo

**Comment by RaymondSchnyder** [comment]
Okay, you dont want to share your vendor blobs.
Thats fine.
But could you atleast update the local_manifests file for beckam?
I tried to build the exact same build as you did, but i fail terribly at booting. It just wont boot.

**Comment by frantisheq** [comment]
sorry for late response. Erfan Abdi asked me to not share vendor, you'll need to ask him to get access to
https://github.com/erfanoabdi/proprietary_vendor_motorola

manifest updated
https://github.com/frantisheq/local_manifests/blob/lineage-16.0/beckham.xml

building with opengapps:
export TMPDIR=/home/username/.tmpdir

repo sync --force-sync
source build/envsetup.sh

#battery mod
repopick -f 227142
repopick 237140
repopick 237141
repopick 237142

breakfast beckham
make installclean

source build/envsetup.sh
brunch beckham

**Comment by RaymondSchnyder** [comment]
Something is weird in your newest update.
I cannot install it with the lineage updater (broke the phone)
I cannot install it with TWRP (broke the phone) 

Also what TWRP version  are you using?
The newest official one seems to not work with the pie encryption (3.2.3-1)

**Comment by RaymondSchnyder** [comment]
Okay, as it seems, it is needed to factory wipe the phone AND internal storage to install an update.
Before i did that, it wouldnt boot.
Now i have another problem:
- I cant enable WLAN (I reset the WiFi Settings, i cleared the cache, i rebooted countless times, its still stock, no magisk or similar software installed)
- The MotoManager is still outdated and cant be updated in the PlayStore (Is this on purpose?)
- Encryption disabled on default (I think this is on purpose because there is no TWRP build which can decrypt the Pie FDE)

**Comment by RaymondSchnyder** [comment]
I installed the brazilian pie update on my phone (from motorola)
Do you want me to extract the vendor blobs? @frantisheq

**Comment by frantisheq** [comment]
thanks but no, i did it already
